### ISSUE TITLE
Git Submodule does not work with GerritHub

### ISSUE THREAD

**Issue by lookeypl** [nfprojects/nfengine#119]
Cloning nfEngine through GerritHub (which is a preferred way to go) does not contain Git Submodule informations about nfEngineDeps. Investigate and fix if possible.

**Steps to reproduce:**
1. Login to GerritHub -> Projects -> List
2. Search for "nfengine", click on nfprojects/nfengine
3. Switch to "General" tab, copy clone command, paste it onto terminal and execute
4. `cd nfengine`
5. `git submodule update --init`

**What should happen:**
Git should clone nfEngineDeps and download the submodule

**What happens:**
Nothing

**Workaround:**
Right now the only way is to clone GitHub repo - submodules work as they should, so cloning nfEngineDeps is possible. Then, Gerrit repo link needs to be manually added using `git remote add`

**Comment by mkulagowski** [comment]
Well...the problem is as simple as can be:
&bull;When cloning from GerritHub you start on branch _master_
&bull;When cloning from GitHub you start on branch _devel_

If on ANY of these You do:
`git checkout master`
`git submodules init`
it won't work.

If on ANY of these You do:
`git checkout devel`
`git submodules init`
it will work.

README on _master_ does not say to use git submodules - everything's in order then ;)

Yet I'd suggest to make even a small update to master branch, cause it looks HORRIBLE. It's really outdated and incomplete in every way - I think it'd be nice to have at least the folder structure or sth.

**Comment by lookeypl** [comment]
As for updating master... Read README.md, or https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows ;)

Thanks for the info. It looks like GerritHub is to blame for incorrect default branch. I will fix that in the settings.

**Comment by lookeypl** [comment]
Fixed in GerritHub settings. Closing, thanks for the help.
