### ISSUE TITLE
Improve tests.py script

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#157]
- [x] Remove sleep https://github.com/nfprojects/nfengine/blob/devel/Scripts/tests.py#L71 which slows tests execution by a significant factor.
- [x] Replace "|/-\" animation with something like that: "Running testcase 4/124...". List of testcases can be obtained with `--gtest_list_tests` option.
- [x] Print time elapsed (per test exec and total).
- [x] Improvements to printed lines when tests fail:
  - The script provides a looong line: `python <full_path_to_root_engine>/Scripts/tests.py <args n stuff>`. Considering the fact we use a shebang and Scripts/tests.py is an executable. I suggest assuming we will be in the root engine directory and removing two beginning parts - `python` and `<full_path>`.
  - Adding a default -v option in the printed line. Usually when tests fail, we want to exactly see a verbose output of it.

**Comment by lookeypl** [comment]
I do agree with second point, however only when this will be kept within one line. I do not want "quiet mode" in tests to spam the console output.

**Comment by mkulagowski** [comment]
1. Sleep was only for animation purpose, so it does look like an animation instead of psycho-fan
2. Animation is kept in one line (text is just overwritten) and so will be those lines with testcases.
3. So which one should it be? Should it go per single test (e.x. x64 nfCoreTest, win32 nfCoreTest, etc) or per single execution of tests.py ?

**Comment by lookeypl** [comment]
1. I do agree and we thought so too. However, this increases the time of our test execution drastically. That's why we decided to remove it.
2. :+1:
3. TBH I think this should be an additional thing, with --time option or sth (of course if @Witek902 agrees). If you provide --time, it should print both times - per test and overall.

As for the task, I added some one more bonus enhancement that went through my head recently.

**Comment by Witek902** [comment]
:+1:

**Comment by mkulagowski** [comment]
Okay, I've done all that's been left to do in [this commit](https://review.gerrithub.io/#/c/270660).

...of course apart from this, as it is already included (--args option):

> Passing additional arguments to test executables. For example nfRendererTest accepts --renderer flag.

**Comment by mkulagowski** [comment]
Merged.

Please update the description and close the issue.

**Comment by Witek902** [comment]
What about the last point?

**Comment by lookeypl** [comment]
The lines are shortened as well, and -v is added. Closing, GJ
